/// app metadata
library meta;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"google_vision","version":"1.2.0+5","homepage":"https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision","environment":{"sdk":">=3.2.0 <4.0.0"},"description":"Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into cross platform applications.","dependencies":{"args":"^2.4.2","collection":"^1.18.0","crypto_keys_plus":"^0.4.0","dio":"^5.4.1","http":"^1.2.1","image":"^4.1.7","jose_plus":"^0.4.3","json_annotation":"^4.8.1","retrofit":"^4.1.0","universal_io":"^2.2.2"},"dev_dependencies":{"build_runner":"^2.4.8","grinder":"^0.9.5","json_serializable":"^6.7.1","lints":"^3.0.0","melos":"^5.1.0","publish_tools":"^0.1.0+15","retrofit_generator":"^8.1.0","test":"^1.25.2"},"executables":{"vision":""},"repository":"https://github.com/faithoflifedev/google_vision"}');
