/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into cross platform applications., homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision, documentation: null, repository: https://github.com/faithoflifedev/google_vision, issueTracker: null, name: google_vision, publish_to: null, version: 2.0.0+6}');
