name: google_vision_workspace
repository: https://github.com/faithoflifedev/google_vision_workspace

packages:
  - packages/**

categories:
  document:
    - packages/google_vision
    - packages/google_vision_flutter


scripts:
  analyze:
    exec: dart analyze .
    failFast: true

  dep:
    exec: dart pub get

  build:
    exec: dart run build_runner build
    failFast: true
    packageFilters:
      fileExists: melos_google_vision.iml
    select-package:
      depends-on: build_runner    

  cleanup:
    packageFilters:
      fileExists: google_vision_flutter.iml
    steps:
      - flutter clean
      - flutter pub get

  format:
    exec: dart format .
    failFast: true

  doc:
    exec: dart doc .
    failFast: true
    packageFilters:
      ignore:
        - "*example*"
        - "*demo*"

  meta:
    exec: grind 'pt-meta'
    failFast: true
    packageFilters:
      ignore:
        - "*example*"
        - "*demo*"
    description: Run metadata generator for all packages.

  pana:
    exec: pana --no-dartdoc .
    packageFilters:
      ignore:
        - "*example*"
        - "*demo*"    
    description: Run pana checks for all packages.

  markdown:
    exec: grind 'pt-markdown'
    packageFilters:
      ignore:
        - "*example*"
        - "*demo*"    
    description: Run markdown generator for all packages.

  prep:
    steps:
      - melos run build
      - melos run meta
      - melos run markdown
      - melos run format
      - melos run analyze
    description: Run prep steps for dart and flutter.

  # prep:flutter:
  #   run: melos run build && melos run meta && melos run markdown && melos run analyze && melos run format
  #   description: Run prep steps Flutter.

  ## TODO: Add commit steps for Dart and Flutter packages.

  # commit:dart:
  #   run: melos exec git add .; git commit -m "chore(release); git push origin main"
  #   description: Commit changes for Dart package.

  # commit:flutter:
  #   run: melos exec git add .; git commit -m "chore(release)"; git push origin main
  #   description: Commit changes for Flutter package.

  publish:real:dart:
    run: melos exec --ignore="google_vision_flutter" dart pub publish --force
    description: Real publish for Google_Vision Package.

  publish:real:flutter:
    run: melos exec --ignore="google_vision" flutter pub publish --force
    description: Real publish for Google_Vision Package.

  publish:flutter:
    run: melos run meta && melos run analyze && melos run format && melos run markdown && melos run dryrun:flutter
    description: Run `dart publish` for all packages.

  dryrun:dart:
    run: melos exec --ignore="google_vision_flutter" dart pub publish --dry-run
    description: Run `dart publish` for Dart package.

  dryrun:flutter:
    run: melos exec --ignore="google_vision_flutter" flutter pub publish --dry-run
    description: Run `flutter pub publish` for Flutter package.

  # clean:deep:
  #   run: git clean -x -d -f -q
  #   description: Clean things very deeply, can be used to establish "pristine checkout" status.
