name: google_vision_examples
description: examples for google_vision
version: 0.0.1
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision

publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  pcanvas: ^1.1.2
  google_vision:
    path: ../
  mime: ^2.0.0
  universal_io: ^2.2.2
