/// app metadata
library meta;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"google_vision_flutter","version":"1.3.0+2","homepage":"https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision_flutter","environment":{"sdk":">=3.2.0 <4.0.0","flutter":">=3.16.0"},"description":"Add Google Visions image labeling, face, logo, and landmark detection into your Flutter applications.","dependencies":{"flutter_image_converter":"^0.3.3","google_vision":"^1.3.0+2","flutter":{"sdk":"flutter"}},"dev_dependencies":{"flutter_lints":"^4.0.0","grinder":"^0.9.5","publish_tools":"^1.0.0+4"},"repository":"https://github.com/faithoflifedev/google_vision"}');
