/// app metadata
library;

// DO NOT EDIT THIS FILE
// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"google_vision_flutter","version":"2.0.0+3","homepage":"https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision_flutter","environment":{"sdk":">=3.2.0 <4.0.0","flutter":">=3.16.0"},"description":"Add Google Visions image labeling, face, logo, and landmark detection into your Flutter applications.","dependencies":{"dio":"^5.7.0","flutter_image_converter":"^0.4.1","google_vision":"^2.0.0","image":"^4.2.0","loggy":"^2.0.3","flutter":{"sdk":"flutter"}},"dev_dependencies":{"flutter_lints":"^5.0.0","grinder":"^0.9.5","publish_tools":"^1.0.0+5"},"repository":"https://github.com/faithoflifedev/google_vision","topics":["api","widget","flutter","image","document"],"funding":["https://www.buymeacoffee.com/faithoflif2"]}');
