/// DO NOT EDIT THIS FILE
/// THIS FILE IS AUTOMATICALLY OVER WRITTEN BY PublishTools
import 'dart:convert' show json;

final pubSpec = json.decode(
    '{"name":"google_vision","version":"1.1.0+2","homepage":"https://github.com/faithoflifedev/google_vision","environment":{"sdk":">=3.0.0 <4.0.0"},"description":"Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into applications.","dependencies":{"args":"^2.4.2","color":"^3.0.0","crypto_keys_plus":"^0.4.0","dio":"^5.3.2","http":"^1.1.0","image":"^4.0.17","jose_plus":"^0.4.3","json_annotation":"^4.8.1","retrofit":"^4.0.1","universal_io":"^2.2.2"},"dev_dependencies":{"build_runner":"^2.4.6","grinder":"^0.9.4","json_serializable":"^6.7.1","lints":"^2.1.1","publish_tools":"^0.1.0+11","retrofit_generator":"^8.0.0","test":"^1.24.6"},"executables":{"vision":""},"repository":"https://github.com/faithoflifedev/google_vision"}');
