name: vision_demo
description: A simple app to test the google_vision_flutter package

publish_to: none

version: 1.0.0+3

environment:
  sdk: ^3.8.0

dependencies:
  color: ^3.0.0
  google_vision_flutter: ^2.0.0+7
  # google_vision_flutter:
  #   path: ../
  loggy: ^2.0.3
  syncfusion_flutter_pdfviewer: ^30.2.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/allswell.pdf
    - assets/census2010.jpg
    - assets/cn_tower.jpg
    - assets/dj.jpg # https://commons.wikimedia.org/wiki/Category:Images#/media/File:DJ_Kelblizz.jpg
    - assets/google_logo.jpg
    - assets/service_credentials.json
    - assets/setagaya_small.jpg
    - assets/structures.png
    - assets/young-man-smiling.jpg
